version: "3.8"

services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile # You'll need to create this Dockerfile
    ports:
      - "4200:4200" # Web client new port
      - "4300:4300" # Server new port
    volumes:
      - ../:/usr/src/app # Mount the whole monorepo
      # Add more specific volumes if needed for node_modules to avoid overwriting
      - /usr/src/app/apps/web/node_modules
      - /usr/src/app/apps/server/node_modules
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - SUPERTOKENS_CORE_URL=${SUPERTOKENS_CORE_URL} # Will pick up from .env or host environment
      - SUPERTOKENS_API_KEY=${SUPERTOKENS_API_KEY} # For managed SuperTokens API Key
      - API_DOMAIN=${API_DOMAIN:-http://localhost:4300} # Updated fallback
      - WEB_DOMAIN=${WEB_DOMAIN:-http://localhost:4200} # Updated fallback
    # command: sh -c "cd apps/server && yarn start & cd ../web && yarn dev" # Example command, adjust as needed

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: pustak
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pustak
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
